#REGISTER_DB=postgres://me:12345@postgres:5432/register_db
version: "3"

services:
        app:
                build: .
                image: $PATH_TO_DOCKERHUB/go_react_socialnetwork:ver_$PATCH_VERSION
                command: ./app
                restart: always
                ports:
                        - "8090:8090"
                depends_on:
                        - postgres
                        - redis
        postgres:
                image: postgres
                restart: always
                volumes:
                        - "./databases/pg:/var/lib/postgresql/data"
                environment:
                        POSTGRES_USER: $PG_USER
                        POSTGRES_PASSWORD: $PG_PASS
                        POSTGRES_DB: $PG_DBNAME
                expose:
                        - "5432"
        redis:
                image: 'bitnami/redis:latest'
                restart: always
                environment:
                        - ALLOW_EMPTY_PASSWORD=yes
                expose: 
                        - "6379"
