#REGISTER_DB=postgres://me:12345@postgres:5432/register_db
version: "3"

services:
        app:
                build: .
                image: social-network:latest
                command: ./app
                restart: always
                ports:
                        - "8090:8090"
                depends_on:
                        - postgres
                        - redis
        postgres:
                image: postgres
                restart: always
                volumes:
                        - "./databases/pg:/var/lib/postgresql/data"
                environment:
                        POSTGRES_USER: me
                        POSTGRES_PASSWORD: 12345
                        POSTGRES_DB: my_coursework_db
                expose:
                        - "5432"
        redis:
                image: 'bitnami/redis:latest'
                environment:
                        - ALLOW_EMPTY_PASSWORD=yes
                expose: 
                        - "6379"
