name: Social_network_CI

  
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ github-actions/test ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "my_testing"
  server_launch:
    runs-on: ubuntu-latest
        
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: launch_server
      run: docker-compose up -d
      env:
        PATH: ${{ secrets.DOCKER_USERNAME }} 
        VER: '1234'
        PG_USER: ${{ secrets.PGUSER }} 
        PG_PASS: ${{ secrets.PGPASSWORD }} 
        PG_DBNAME: ${{ secrets.PGDBNAME }}

    - name: check running containers
      run: docker ps -a
    
    - name: run tests
      run: sudo docker build -t test tests/. && sudo docker run --network host test
    
    - name: push to docker
      run: | 
            docker login --username ${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            docker push araxal/go_react_socialnetwork:test
